import prisma from "@/lib/prisma"
import { NextResponse } from "next/server"

export async function POST() {
   const createServer = await prisma.server.create({
      data: {
         id: "13478239-1b1a-4b0a-9b0a-0a0a0a0a0a0a",
      },
      include: {
         datas: true,
      },
   })

   const createData = await prisma.serverData.createMany({
      data: [
         {
            email: "dumero@undu.gm",
            number: "(956) 258-4737",
            address: "1518 Uluwef Trail",
            age: "42",
            serverId: createServer.id,
         },
         {
            email: "omalicic@weer.tt",
            number: "(780) 487-5648",
            address: "751 Nigu Glen",
            age: "41",
            serverId: createServer.id,
         },
         {
            email: "nugbokuh@ujipaw.ug",
            number: "(725) 609-9480",
            address: "1521 Bebva Highway",
            age: "26",
            serverId: createServer.id,
         },
         {
            email: "cekfacfi@nu.no",
            number: "(980) 317-1446",
            address: "1718 Utune Pike",
            age: "9",
            serverId: createServer.id,
         },
         {
            email: "jis@ob.au",
            number: "(789) 323-4348",
            address: "415 Fehba Key",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "icuzas@pe.ad",
            number: "(929) 859-7700",
            address: "1798 Dujcez Park",
            age: "20",
            serverId: createServer.id,
         },
         {
            email: "kaupur@tugdez.it",
            number: "(962) 975-8647",
            address: "1147 Wada Heights",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "cawu@majad.sd",
            number: "(854) 922-2322",
            address: "527 Pekit Extension",
            age: "6",
            serverId: createServer.id,
         },
         {
            email: "uda@lagoc.zm",
            number: "(489) 287-8176",
            address: "1164 Inoawo Square",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "emiwuwuv@am.si",
            number: "(727) 980-8926",
            address: "647 Vajiju Pike",
            age: "2",
            serverId: createServer.id,
         },
         {
            email: "wetog@kimiposip.pe",
            number: "(649) 389-4908",
            address: "359 Wawo Circle",
            age: "39",
            serverId: createServer.id,
         },
         {
            email: "nib@ewodaga.io",
            number: "(604) 584-1578",
            address: "1161 Oseik Parkway",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "ta@gevof.mn",
            number: "(485) 615-2421",
            address: "1616 Dobaj Path",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "ozluno@nofopo.ht",
            number: "(365) 427-2015",
            address: "1005 Toji View",
            age: "28",
            serverId: createServer.id,
         },
         {
            email: "so@husor.ng",
            number: "(805) 406-7557",
            address: "282 Wotem Key",
            age: "26",
            serverId: createServer.id,
         },
         {
            email: "zeisa@pohvog.dz",
            number: "(725) 503-3551",
            address: "1163 Bicce Drive",
            age: "12",
            serverId: createServer.id,
         },
         {
            email: "di@mig.ac",
            number: "(378) 481-7270",
            address: "782 Gadker Street",
            age: "2",
            serverId: createServer.id,
         },
         {
            email: "reowo@cigmoh.zw",
            number: "(574) 470-2199",
            address: "1201 Olwo Ridge",
            age: "39",
            serverId: createServer.id,
         },
         {
            email: "ricoma@mosuklem.re",
            number: "(574) 459-7931",
            address: "1000 Emlec Place",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "obzec@nitol.sb",
            number: "(886) 851-2017",
            address: "1319 Fopsi Manor",
            age: "8",
            serverId: createServer.id,
         },
         {
            email: "nos@unoakrec.ca",
            number: "(375) 316-1529",
            address: "1935 Vovpe Highway",
            age: "17",
            serverId: createServer.id,
         },
         {
            email: "wosob@bitbug.de",
            number: "(661) 420-8392",
            address: "1959 Fofbuw Street",
            age: "",
            serverId: createServer.id,
         },
         {
            email: "rep@gocer.ac",
            number: "(208) 765-9901",
            address: "1781 Libu Turnpike",
            age: "15",
            serverId: createServer.id,
         },
         {
            email: "hapnecbel@tinne.ws",
            number: "(780) 350-2281",
            address: "1996 Rowhu Circle",
            age: "21",
            serverId: createServer.id,
         },
         {
            email: "dum@ikihi.us",
            number: "(629) 725-3399",
            address: "605 Caza Pike",
            age: "15",
            serverId: createServer.id,
         },
         {
            email: "zegu@monu.tr",
            number: "(951) 778-2013",
            address: "864 Givdiv Road",
            age: "10",
            serverId: createServer.id,
         },
         {
            email: "gaonpu@ejerusron.bs",
            number: "(452) 309-9446",
            address: "1552 Cevfu Place",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "pet@gum.bg",
            number: "(312) 218-6594",
            address: "489 Efmaj Pass",
            age: "37",
            serverId: createServer.id,
         },
         {
            email: "ud@kimpon.fr",
            number: "(284) 774-3820",
            address: "1740 Afju Road",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "vorin@siuju.sc",
            number: "(459) 835-5677",
            address: "1134 Bosmi Trail",
            age: "14",
            serverId: createServer.id,
         },
         {
            email: "kumu@fieh.gf",
            number: "(533) 655-4161",
            address: "1812 Ehopad Key",
            age: "25",
            serverId: createServer.id,
         },
         {
            email: "difoswop@pic.at",
            number: "(279) 372-2790",
            address: "1675 Umuhu Extension",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "lipmo@jabfun.mo",
            number: "(935) 594-4774",
            address: "1891 Madsak Grove",
            age: "9",
            serverId: createServer.id,
         },
         {
            email: "wenma@pula.es",
            number: "(354) 435-7717",
            address: "250 Dapar View",
            age: "22",
            serverId: createServer.id,
         },
         {
            email: "hiw@ugisair.mv",
            number: "(365) 610-6473",
            address: "439 Badwin Lane",
            age: "4",
            serverId: createServer.id,
         },
         {
            email: "oluze@woemlul.jo",
            number: "(837) 557-7952",
            address: "121 Merfic Court",
            age: "40",
            serverId: createServer.id,
         },
         {
            email: "ziedodat@fub.hk",
            number: "(686) 718-6019",
            address: "817 Nejes Street",
            age: "33",
            serverId: createServer.id,
         },
         {
            email: "pawro@supcignek.yt",
            number: "(220) 215-1084",
            address: "1386 Wanud Pass",
            age: "33",
            serverId: createServer.id,
         },
         {
            email: "geuwrik@ke.eh",
            number: "(574) 894-1531",
            address: "1520 Cujo Trail",
            age: "11",
            serverId: createServer.id,
         },
         {
            email: "zufto@woh.ht",
            number: "(756) 412-1793",
            address: "236 Uksa Ridge",
            age: "37",
            serverId: createServer.id,
         },
         {
            email: "ihuuva@cagati.gu",
            number: "(757) 821-9587",
            address: "403 Gumib Park",
            age: "3",
            serverId: createServer.id,
         },
         {
            email: "juzirvu@zomcoc.ax",
            number: "(969) 363-4540",
            address: "1764 Zedpe Park",
            age: "10",
            serverId: createServer.id,
         },
         {
            email: "mezasuv@be.si",
            number: "(913) 938-8923",
            address: "906 Ulojed Ridge",
            age: "7",
            serverId: createServer.id,
         },
         {
            email: "nezekat@wug.ug",
            number: "(284) 803-6837",
            address: "830 Azcul Park",
            age: "3",
            serverId: createServer.id,
         },
         {
            email: "lunew@ze.mp",
            number: "(689) 838-5503",
            address: "1681 Vubco River",
            age: "3",
            serverId: createServer.id,
         },
         {
            email: "fiuvpos@keso.fr",
            number: "(448) 849-2643",
            address: "278 Ginav Park",
            age: "35",
            serverId: createServer.id,
         },
         {
            email: "za@cam.lv",
            number: "(231) 387-5438",
            address: "539 Gail Highway",
            age: "42",
            serverId: createServer.id,
         },
         {
            email: "ic@amakehduf.ai",
            number: "(408) 469-6285",
            address: "286 Ogmop Lane",
            age: "28",
            serverId: createServer.id,
         },
         {
            email: "foohiuz@bi.ca",
            number: "(303) 826-2871",
            address: "1216 Tife Circle",
            age: "31",
            serverId: createServer.id,
         },
         {
            email: "bed@ad.cn",
            number: "(273) 329-3045",
            address: "349 Wadren Pass",
            age: "28",
            serverId: createServer.id,
         },
         {
            email: "zat@bavzo.ly",
            number: "(659) 493-1918",
            address: "1504 Umoreb Junction",
            age: "34",
            serverId: createServer.id,
         },
         {
            email: "taeb@teh.fj",
            number: "(924) 315-5152",
            address: "898 Figi River",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "fipug@jen.ni",
            number: "(322) 860-1857",
            address: "1328 Moela Point",
            age: "30",
            serverId: createServer.id,
         },
         {
            email: "waduupe@refmovpop.ao",
            number: "(284) 415-4446",
            address: "499 Hegelo Ridge",
            age: "39",
            serverId: createServer.id,
         },
         {
            email: "wuvil@ahi.ec",
            number: "(779) 212-8977",
            address: "216 Relful Glen",
            age: "2",
            serverId: createServer.id,
         },
         {
            email: "mu@vecafapo.lk",
            number: "(843) 989-8366",
            address: "1878 Leci River",
            age: "40",
            serverId: createServer.id,
         },
         {
            email: "sebbi@igdosi.uy",
            number: "(968) 737-6752",
            address: "1008 Jeje Court",
            age: "21",
            serverId: createServer.id,
         },
         {
            email: "gu@pad.ag",
            number: "(260) 977-4241",
            address: "634 Kaje Pass",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "huwig@povza.mp",
            number: "(338) 753-5461",
            address: "723 Gipzap Extension",
            age: "35",
            serverId: createServer.id,
         },
         {
            email: "lot@woru.re",
            number: "(300) 495-8332",
            address: "1486 Udipaw Way",
            age: "18",
            serverId: createServer.id,
         },
         {
            email: "pikjemar@loajipen.gh",
            number: "(255) 461-8640",
            address: "729 Zopam Path",
            age: "17",
            serverId: createServer.id,
         },
         {
            email: "wilafuki@ob.kn",
            number: "(967) 966-3920",
            address: "694 Ficfir Park",
            age: "9",
            serverId: createServer.id,
         },
         {
            email: "ri@ahovifpuz.ba",
            number: "(489) 563-6358",
            address: "875 Zupzum Point",
            age: "23",
            serverId: createServer.id,
         },
         {
            email: "go@uv.ai",
            number: "(422) 300-7848",
            address: "1599 Izho Pike",
            age: "18",
            serverId: createServer.id,
         },
         {
            email: "utahimug@hamodo.pr",
            number: "(806) 355-2700",
            address: "329 Lijib Pike",
            age: "6",
            serverId: createServer.id,
         },
         {
            email: "za@zulecu.iq",
            number: "(650) 275-6051",
            address: "218 Bigtu Grove",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "hilec@tomafode.fi",
            number: "(723) 751-5809",
            address: "2000 Kevo River",
            age: "18",
            serverId: createServer.id,
         },
         {
            email: "kiva@ve.gg",
            number: "(480) 649-7219",
            address: "370 Jejibe Place",
            age: "31",
            serverId: createServer.id,
         },
         {
            email: "bo@jeh.gb",
            number: "(588) 240-1552",
            address: "839 Upnep Pass",
            age: "27",
            serverId: createServer.id,
         },
         {
            email: "migsi@tachon.al",
            number: "(941) 999-3299",
            address: "982 Nofku Loop",
            age: "27",
            serverId: createServer.id,
         },
         {
            email: "puvu@cogej.ls",
            number: "(474) 416-3434",
            address: "1861 Apafuh Point",
            age: "8",
            serverId: createServer.id,
         },
         {
            email: "mohsu@vuf.tw",
            number: "(587) 810-7430",
            address: "1743 Sagiji Parkway",
            age: "3",
            serverId: createServer.id,
         },
         {
            email: "wobasirun@riw.hk",
            number: "(534) 525-5780",
            address: "1692 Ruep Junction",
            age: "25",
            serverId: createServer.id,
         },
         {
            email: "oh@tubjeeco.ni",
            number: "(423) 654-1384",
            address: "551 Dorbe Heights",
            age: "12",
            serverId: createServer.id,
         },
         {
            email: "kuf@etsuri.fm",
            number: "(658) 409-5772",
            address: "933 Rafivu Pike",
            age: "18",
            serverId: createServer.id,
         },
         {
            email: "da@ne.aw",
            number: "(827) 769-4288",
            address: "563 Hinu Mill",
            age: "",
            serverId: createServer.id,
         },
         {
            email: "kirfuh@acjisvol.do",
            number: "(335) 344-9800",
            address: "966 Zovazi Glen",
            age: "40",
            serverId: createServer.id,
         },
         {
            email: "ze@mehgaw.edu",
            number: "(448) 981-6305",
            address: "780 Hovva Center",
            age: "6",
            serverId: createServer.id,
         },
         {
            email: "hojmagim@kih.sn",
            number: "(427) 977-4078",
            address: "1663 Leja View",
            age: "16",
            serverId: createServer.id,
         },
         {
            email: "sacwouj@pevraju.co.uk",
            number: "(951) 331-3916",
            address: "1778 Okago Key",
            age: "28",
            serverId: createServer.id,
         },
         {
            email: "vacahi@ru.mk",
            number: "(227) 697-3718",
            address: "1500 Tijiz Street",
            age: "42",
            serverId: createServer.id,
         },
         {
            email: "ceejini@holu.la",
            number: "(947) 223-5116",
            address: "202 Vemap Street",
            age: "8",
            serverId: createServer.id,
         },
         {
            email: "di@jigru.gp",
            number: "(319) 717-8600",
            address: "162 Idde Lane",
            age: "9",
            serverId: createServer.id,
         },
         {
            email: "wen@amke.ai",
            number: "(769) 942-1177",
            address: "1166 Lubep View",
            age: "12",
            serverId: createServer.id,
         },
         {
            email: "temordu@himneem.it",
            number: "(789) 712-4315",
            address: "59 Wurho Square",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "te@lalfe.gu",
            number: "(221) 484-3221",
            address: "1054 Nacsi Grove",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "wavroc@jupzor.cu",
            number: "(831) 489-7686",
            address: "1826 Saev Parkway",
            age: "41",
            serverId: createServer.id,
         },
         {
            email: "ze@zuc.mv",
            number: "(351) 516-6182",
            address: "1198 Teza Key",
            age: "3",
            serverId: createServer.id,
         },
         {
            email: "uchof@zofuze.sv",
            number: "(265) 244-5930",
            address: "1066 Fitvi Key",
            age: "21",
            serverId: createServer.id,
         },
         {
            email: "hurumeaka@mumazi.fm",
            number: "(611) 850-1555",
            address: "1421 Ahji Place",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "tepde@foz.rs",
            number: "(952) 429-1297",
            address: "1164 Ahha Square",
            age: "38",
            serverId: createServer.id,
         },
         {
            email: "ahsufo@ti.pn",
            number: "(200) 631-4874",
            address: "585 Sulro Court",
            age: "1",
            serverId: createServer.id,
         },
         {
            email: "obopolaj@wobafpe.fr",
            number: "(855) 570-2331",
            address: "1411 Dibsij Key",
            age: "13",
            serverId: createServer.id,
         },
         {
            email: "hi@piw.im",
            number: "(254) 235-2879",
            address: "5 Utoval Path",
            age: "22",
            serverId: createServer.id,
         },
         {
            email: "bihham@buvwe.no",
            number: "(701) 410-2400",
            address: "98 Fium Manor",
            age: "13",
            serverId: createServer.id,
         },
         {
            email: "ho@eri.pa",
            number: "(418) 366-8257",
            address: "1693 Uvfun Heights",
            age: "4",
            serverId: createServer.id,
         },
         {
            email: "zurzu@mal.zm",
            number: "(379) 556-4249",
            address: "1144 Tauh Pike",
            age: "16",
            serverId: createServer.id,
         },
         {
            email: "peri@damcimon.cl",
            number: "(970) 578-1857",
            address: "629 Temo Path",
            age: "27",
            serverId: createServer.id,
         },
         {
            email: "bu@ut.nc",
            number: "(840) 868-5648",
            address: "585 Peli Circle",
            age: "27",
            serverId: createServer.id,
         },
         {
            email: "zidelguh@zih.net",
            number: "(381) 300-6656",
            address: "553 Enlav Lane",
            age: "6",
            serverId: createServer.id,
         },
         {
            email: "jamudcu@tili.kn",
            number: "(239) 693-2828",
            address: "634 Vohig Point",
            age: "40",
            serverId: createServer.id,
         },
         {
            email: "we@er.af",
            number: "(344) 433-8883",
            address: "909 Okka Drive",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "ana@lazonros.im",
            number: "(201) 810-8065",
            address: "11 Maze Center",
            age: "25",
            serverId: createServer.id,
         },
         {
            email: "kof@relwi.mw",
            number: "(944) 908-5526",
            address: "1522 Kikew View",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "il@ulaisu.lk",
            number: "(963) 938-5960",
            address: "1106 Belhus Manor",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "irupfef@ac.so",
            number: "(623) 747-5730",
            address: "602 Vicu Point",
            age: "18",
            serverId: createServer.id,
         },
         {
            email: "bazagaova@toke.al",
            number: "(421) 325-2079",
            address: "982 Wemsam Pike",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "far@hiffuuso.sd",
            number: "(239) 550-1261",
            address: "1893 Opoek Ridge",
            age: "37",
            serverId: createServer.id,
         },
         {
            email: "gavvi@cir.no",
            number: "(351) 769-2211",
            address: "1384 Detuj Mill",
            age: "38",
            serverId: createServer.id,
         },
         {
            email: "wo@canum.as",
            number: "(817) 515-4376",
            address: "1325 Fegwo Way",
            age: "24",
            serverId: createServer.id,
         },
         {
            email: "ru@cuffogi.hk",
            number: "(479) 504-1659",
            address: "458 Dene Square",
            age: "21",
            serverId: createServer.id,
         },
         {
            email: "puffukkem@epi.fk",
            number: "(467) 555-6099",
            address: "1230 Depoz Pass",
            age: "31",
            serverId: createServer.id,
         },
         {
            email: "ges@koovwu.si",
            number: "(418) 683-7568",
            address: "460 Diza Lane",
            age: "29",
            serverId: createServer.id,
         },
         {
            email: "girijvuk@na.lu",
            number: "(604) 903-5727",
            address: "1670 Pitmi Junction",
            age: "12",
            serverId: createServer.id,
         },
         {
            email: "uvokubolo@wohcub.tz",
            number: "(771) 519-5121",
            address: "415 Ille Path",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "aj@wazaiv.af",
            number: "(283) 699-1182",
            address: "780 Esfod Lane",
            age: "6",
            serverId: createServer.id,
         },
         {
            email: "ugsaczi@mel.bh",
            number: "(424) 689-6646",
            address: "346 Necew View",
            age: "36",
            serverId: createServer.id,
         },
         {
            email: "gemehzu@colwin.om",
            number: "(902) 840-9649",
            address: "1588 Adma Park",
            age: "16",
            serverId: createServer.id,
         },
         {
            email: "fujjo@fedofbuz.net",
            number: "(409) 342-5951",
            address: "863 Gurhir River",
            age: "12",
            serverId: createServer.id,
         },
         {
            email: "lipuso@ge.cu",
            number: "(214) 773-6996",
            address: "1624 Ulefa Extension",
            age: "17",
            serverId: createServer.id,
         },
         {
            email: "val@ziwpom.bt",
            number: "(302) 920-2747",
            address: "1568 Afvo Way",
            age: "19",
            serverId: createServer.id,
         },
         {
            email: "cajev@su.so",
            number: "(982) 259-4450",
            address: "604 Garci Extension",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "meeretep@niwdeb.vi",
            number: "(862) 247-9884",
            address: "1257 Hosli Pass",
            age: "37",
            serverId: createServer.id,
         },
         {
            email: "finvuze@gowoccoc.wf",
            number: "(714) 749-4703",
            address: "2000 Emla View",
            age: "11",
            serverId: createServer.id,
         },
         {
            email: "telifucu@din.ua",
            number: "(639) 979-1103",
            address: "543 Ciha Mill",
            age: "34",
            serverId: createServer.id,
         },
         {
            email: "gi@fol.ls",
            number: "(775) 208-3383",
            address: "1748 Puhjat Glen",
            age: "33",
            serverId: createServer.id,
         },
         {
            email: "rahrev@jo.aq",
            number: "(747) 481-4290",
            address: "341 Zeuce Street",
            age: "32",
            serverId: createServer.id,
         },
         {
            email: "toc@metzuf.ga",
            number: "(880) 672-2200",
            address: "499 Lafer Drive",
            age: "28",
            serverId: createServer.id,
         },
         {
            email: "boucoze@sa.fm",
            number: "(924) 804-8417",
            address: "962 Kucsir Parkway",
            age: "20",
            serverId: createServer.id,
         },
         {
            email: "ku@vekune.tz",
            number: "(324) 569-3860",
            address: "329 Jire Path",
            age: "7",
            serverId: createServer.id,
         },
      ],
   })

   return NextResponse.json(
      { server: createServer, data: createData },
      { status: 201 }
   )
}
